# Generated by Django 3.2.18 on 2023-06-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_user', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Dni_Id_user', models.IntegerField(max_length=50)),
                ('Pais_dniId_user', models.CharField(max_length=50)),
                ('telefono_user', models.IntegerField(max_length=50)),
                ('email_user', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['id'],
            },
        ),
    ]
